/*==============================================================*/
/* DBMS name:      MySQL 5.0                                    */
/* Created on:     2021/5/10 16:55:53                           */
/*==============================================================*/


drop index U_SYSBOOK_TYPELIST on SYSBOOK;

drop index I_SYSBOOK_TYPECODE on SYSBOOK;

drop table if exists SYSBOOK;

drop index U_FUNC_CODE on SYS_FUNCTION;

drop table if exists SYS_FUNCTION;

drop index U_ROLE_NAME on SYS_ROLE;

drop table if exists SYS_ROLE;

drop table if exists SYS_ROLE_FUNC;

drop index U_USER_NAME on SYS_USER;

drop table if exists SYS_USER;

drop table if exists SYS_USER_ROLE;

/*==============================================================*/
/* Table: SYSBOOK                                               */
/*==============================================================*/
create table SYSBOOK
(
   ID                   bigint not null auto_increment comment 'ID',
   TYPE_CODE            varchar(32) not null comment '类型编号',
   TYPE_NAME            varchar(255) not null comment '类型名称',
   LIST_CODE            varchar(32) not null comment '明细编号',
   LIST_NAME            varchar(255) not null comment '明细名称',
   STATUS               tinyint not null default 1 comment '状态 数据字典条目状态：0:删除，1:有效',
   MODIFY_FLAG          tinyint(1) comment '可修改标志
            0：不可修改
            1：可修改',
   PRI                  int comment '显示顺序',
   REMARK               varchar(200) comment '备注',
   CREATE_TIME          datetime comment '创建时间',
   CREATE_USER          varchar(50) comment '创建用户',
   UPDATE_TIME          datetime comment '修改时间',
   UPDATE_USER          varchar(50) comment '修改用户',
   primary key (ID)
);

alter table SYSBOOK comment '数据字典表';

-- 通用状态 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('COMMON_VALID','通用状态','1','有效',1,1,'通用状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('COMMON_VALID','通用状态','0','无效',1,0,'通用状态',NOW());

-- 通用是否 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('COMMON_YES','通用是否','1','是',1,1,'通用是否',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('COMMON_NO','通用是否','0','否',1,0,'通用是否',NOW());

-- 职业 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','1','政府、企事业机关工作人员',1,1,'职业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','2','专业技术人员',1,1,'职业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','3','职员',1,1,'职业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','4','商务人员',1,1,'职业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','5','第三产业服务人员',1,1,'职业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','6','产业工人',1,1,'职业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','7','农林牧渔业从业者',1,1,'职业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','8','家庭主妇',1,1,'职业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','9','学生',1,1,'职业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','10','私营企业主',1,1,'职业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','11','失业',1,1,'职业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','12','离退休人员',1,1,'职业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('OCCUPATION','职业','13','其他',1,1,'职业',NOW());

-- 学历 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('EDUCATION','学历','1','小学',1,1,'学历',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('EDUCATION','学历','2','初中',1,1,'学历',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('EDUCATION','学历','3','高中',1,1,'学历',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('EDUCATION','学历','4','大专',1,1,'学历',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('EDUCATION','学历','5','本科 ',1,1,'学历',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('EDUCATION','学历','6','硕士 ',1,1,'学历',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('EDUCATION','学历','7','博士 ',1,1,'学历',NOW());

-- 收入 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('INCOME','收入','1','5000元以下',1,1,'收入',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('INCOME','收入','2','5000-9999元',1,1,'收入',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('INCOME','收入','3','10000-14999元',1,1,'收入',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('INCOME','收入','4','15000-19999元',1,1,'收入',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('INCOME','收入','5','20000元及以上',1,1,'收入',NOW());

-- 婚姻状况 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MARRIAGE','婚姻状况','1','单身',1,1,'婚姻状况',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MARRIAGE','婚姻状况','2','恋爱中',1,1,'婚姻状况',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MARRIAGE','婚姻状况','3','已婚',1,1,'婚姻状况',NOW());

-- 偏好 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('PREFERENCE','偏好','1','运动',1,1,'偏好',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('PREFERENCE','偏好','2','旅游',1,1,'偏好',NOW());

-- 余额记录状态 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('RECORD_STATUS','余额记录状态','1','成功',1,1,'余额记录状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('RECORD_STATUS','余额记录状态','2','失败',1,1,'余额记录状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('RECORD_STATUS','余额记录状态','3','已撤销',1,1,'余额记录状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('RECORD_STATUS','余额记录状态','4','已冲正',1,4,'余额记录状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('RECORD_STATUS','余额记录状态','9','处理中',1,9,'余额记录状态',NOW());

-- 用户消息状态 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MESSAGE_STATUS','用户消息状态','0','删除',1,1,'用户消息状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MESSAGE_STATUS','用户消息状态','1','未读',1,1,'用户消息状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MESSAGE_STATUS','用户消息状态','2','已读',1,1,'用户消息状态',NOW());

-- 行业 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('INDUSTRY','行业','1','餐饮',1,1,'行业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('INDUSTRY','行业','2','零售',1,1,'行业',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('INDUSTRY','行业','3','酒店',1,1,'行业',NOW());

-- 银行 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','1','中国工商银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','2','中国农业银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','3','中国银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','4','中国建设银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','5','交通银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','6','中国邮政储蓄银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','7','中国光大银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','8','中国民生银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','9','招商银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','10','中信银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','11','华夏银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','12','上海浦东发展银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','13','平安银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','14','广发银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','15','兴业银行',1,1,'行业',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('BANK','银行','16','上海银行',1,1,'行业',NOW());

-- 商户餐饮类别 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','12','火锅',1,1,'商户餐饮类别',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','13','日本料理',1,1,'商户餐饮类别',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','14','本帮菜',1,1,'商户餐饮类别',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','15','粤菜',1,1,'商户餐饮类别',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','16','川菜',1,1,'商户餐饮类别',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','17','中式快餐',1,1,'商户餐饮类别',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','18','饮品甜品',1,1,'商户餐饮类别',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','19','意大利菜',1,1,'商户餐饮类别',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','20','饮品      ',1,1,'商户餐饮类别',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','21','新加坡菜',1,1,'商户餐饮类别',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','22','东南亚菜',1,1,'商户餐饮类别',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','23','烧烤',1,1,'商户餐饮类别',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('MER_CATEGORY','商户餐饮类别','24','海鲜',1,1,'商户餐饮类别',NOW());

-- 问卷类型 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTIONNAIRE_TYPE','问卷类型','1','普通问卷',1,1,'问卷类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTIONNAIRE_TYPE','问卷类型','2','模板问卷',1,1,'问卷类型',NOW());

-- 问卷状态 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTIONNAIRE_STATUS','问卷状态','0','删除',1,1,'问卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTIONNAIRE_STATUS','问卷状态','1','已保存',1,1,'问卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTIONNAIRE_STATUS','问卷状态','2','待审核',1,1,'问卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTIONNAIRE_STATUS','问卷状态','3','已发布',1,1,'问卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTIONNAIRE_STATUS','问卷状态','4','审核拒绝',1,1,'问卷状态',NOW());

-- 问题类型 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_TYPE','问题类型','1','单选',1,1,'问题类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_TYPE','问题类型','2','多选',1,1,'问题类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_TYPE','问题类型','3','单行填空',1,1,'问题类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_TYPE','问题类型','4','多行填空',1,1,'问题类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_TYPE','问题类型','5','矩阵单选',1,1,'问题类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_TYPE','问题类型','6','矩阵多选',1,1,'问题类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_TYPE','问题类型','7','量表题',1,1,'问题类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_TYPE','问题类型','8','NPS量表',1,1,'问题类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_TYPE','问题类型','9','文件上传',1,1,'问题类型',NOW());

-- 问题显示类型名称 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_SHOW_TYPE','问题显示类型名称','1','单选',1,1,'问题显示类型名称',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_SHOW_TYPE','问题显示类型名称','2','多选',1,1,'问题显示类型名称',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_SHOW_TYPE','问题显示类型名称','3','文字',1,1,'问题显示类型名称',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_SHOW_TYPE','问题显示类型名称','4','文字',1,1,'问题显示类型名称',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_SHOW_TYPE','问题显示类型名称','5','单选',1,1,'问题显示类型名称',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_SHOW_TYPE','问题显示类型名称','6','多选',1,1,'问题显示类型名称',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_SHOW_TYPE','问题显示类型名称','7','评分',1,1,'问题显示类型名称',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_SHOW_TYPE','问题显示类型名称','8','评分',1,1,'问题显示类型名称',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('QUESTION_SHOW_TYPE','问题显示类型名称','9','照片',1,1,'问题显示类型名称',NOW());

-- 任务关联平台 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('TASK_PLATFORM','任务关联平台','1','大众点评',1,1,'任务关联平台',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('TASK_PLATFORM','任务关联平台','9','华垚',1,1,'任务关联平台',NOW());

-- 答卷状态 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('ANSWER_STATUS','答卷状态','1','已领取',1,1,'答卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('ANSWER_STATUS','答卷状态','2','已签到',1,1,'答卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('ANSWER_STATUS','答卷状态','3','未提交',1,1,'答卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('ANSWER_STATUS','答卷状态','4','待审核',1,1,'答卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('ANSWER_STATUS','答卷状态','5','二审待审核',1,1,'答卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('ANSWER_STATUS','答卷状态','6','审核通过',1,1,'答卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('ANSWER_STATUS','答卷状态','7','退回修改',1,1,'答卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('ANSWER_STATUS','答卷状态','8','已取消',1,1,'答卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('ANSWER_STATUS','答卷状态','9','审核失败',1,1,'答卷状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('ANSWER_STATUS','答卷状态','10','超时未完成',1,1,'答卷状态',NOW());
-- 审核业务类型 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('CHECK_TYPE','审核业务类型','1','问卷审核',1,1,'审核业务类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('CHECK_TYPE','审核业务类型','2','任务审核',1,1,'审核业务类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('CHECK_TYPE','审核业务类型','3','答卷审核',1,1,'审核业务类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('CHECK_TYPE','审核业务类型','4','合同审核',1,1,'审核业务类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('CHECK_TYPE','审核业务类型','5','用户资料审核',1,1,'审核业务类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('CHECK_TYPE','审核业务类型','6','商户资料审核',1,1,'审核业务类型',NOW());

-- 商户状态 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MER_STATUS','商户状态','1','正常',1,1,'商户状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MER_STATUS','商户状态','0','删除',1,0,'商户状态',NOW());

-- 门店状态 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('SHOP_STATUS','门店状态','1','正常',1,1,'门店状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('SHOP_STATUS','门店状态','0','删除',1,0,'门店状态',NOW());

-- 超级用户 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('SUPER_USER','超级用户','1','是',1,1,'超级用户',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('SUPER_USER','超级用户','0','否',1,0,'超级用户',NOW());

-- 性别 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('GENDER','性别','1','男',1,1,'性别',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('GENDER','性别','2','女',1,2,'性别',NOW());

-- 大众点评等级 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('DIANPING_LEVEL','大众点评等级','1','1',1,1,'大众点评等级',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('DIANPING_LEVEL','大众点评等级','2','2',1,2,'大众点评等级',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('DIANPING_LEVEL','大众点评等级','3','3',1,3,'大众点评等级',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('DIANPING_LEVEL','大众点评等级','4','4',1,4,'大众点评等级',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('DIANPING_LEVEL','大众点评等级','5','5',1,5,'大众点评等级',NOW());

-- 用户等级 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('GRADE','用户等级','1','1',1,1,'用户等级',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('GRADE','用户等级','2','2',1,2,'用户等级',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('GRADE','用户等级','3','3',1,3,'用户等级',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('GRADE','用户等级','4','4',1,4,'用户等级',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('GRADE','用户等级','5','5',1,5,'用户等级',NOW());

-- 余额记录类型 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('RECORD_TYPE','余额记录类型','1','充值',1,1,'余额记录类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('RECORD_TYPE','余额记录类型','2','撤销',1,2,'余额记录类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('RECORD_TYPE','余额记录类型','3','提现',1,3,'余额记录类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('RECORD_TYPE','余额记录类型','4','冲正',1,4,'余额记录类型',NOW());

-- 审核用户类型--
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('USER_TYPE','审核用户类型','1','系统用户',1,1,'审核用户类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('USER_TYPE','审核用户类型','2','商户',1,2,'审核用户类型',NOW());

-- 附近距离 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('NEARBY_DISTANCE','附近距离','1','2000',1,1,'附近距离',NOW());

-- 任务状态 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('TASK_STATUS','任务状态','0','删除',1,1,'任务状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('TASK_STATUS','任务状态','1','待审核',1,1,'任务状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('TASK_STATUS','任务状态','2','审核中',1,1,'任务状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('TASK_STATUS','任务状态','3','已生效',1,1,'任务状态',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('TASK_STATUS','任务状态','4','审核拒绝',1,1,'任务状态',NOW());

-- 任务类型 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('TASK_TYPE','任务类型','1','秘客任务',1,1,'任务类型',NOW());
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME) VALUES('TASK_TYPE','任务类型','2','即时任务',1,1,'任务类型',NOW());

-- 任务过滤类型 -- 
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('FILTER_TYPE','任务过滤类型','1','用户等级',1,1,'任务过滤类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('FILTER_TYPE','任务过滤类型','2','大众点评等级',1,2,'任务过滤类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('FILTER_TYPE','任务过滤类型','3','年龄',1,3,'任务过滤类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('FILTER_TYPE','任务过滤类型','4','职业',1,4,'任务过滤类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('FILTER_TYPE','任务过滤类型','5','性别',1,5,'任务过滤类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('FILTER_TYPE','任务过滤类型','6','学历',1,6,'任务过滤类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('FILTER_TYPE','任务过滤类型','7','收入',1,7,'任务过滤类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('FILTER_TYPE','任务过滤类型','8','婚姻状况',1,8,'任务过滤类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('FILTER_TYPE','任务过滤类型','9','偏好',1,9,'任务过滤类型',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('FILTER_TYPE','任务过滤类型','10','超级用户',1,10,'任务过滤类型',NOW());

-- 年龄范围 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('AGE_RANGE','年龄范围','1','20岁以下',1,1,'年龄范围',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('AGE_RANGE','年龄范围','2','20-29岁',1,2,'年龄范围',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('AGE_RANGE','年龄范围','3','30-39岁',1,3,'年龄范围',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('AGE_RANGE','年龄范围','4','40-49岁',1,4,'年龄范围',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('AGE_RANGE','年龄范围','5','50-59岁',1,5,'年龄范围',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('AGE_RANGE','年龄范围','6','60-69岁',1,6,'年龄范围',NOW());

-- 收藏类型 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('COLLECTION_TYPE','收藏类型','1','商户',1,1,'收藏类型',NOW());

-- 审核记录类型 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('CHECKRECORD_TYPE','审核记录类型','1','任务',1,1,'审核记录类型',NOW());
    		
-- 审核记录状态 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('CHECK_STATUS','审核记录状态','1','待审核',1,1,'审核记录状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('CHECK_STATUS','审核记录状态','2','审核通过',1,2,'审核记录状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('CHECK_STATUS','审核记录状态','3','审核拒绝',1,3,'审核记录状态',NOW());

-- 审核操作结果 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('CHECK_RESULT','审核结果','1','通过',1,1,'审核结果',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('CHECK_RESULT','审核结果','2','拒绝',1,1,'审核结果',NOW());

-- 签到距离限制 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('SIGNIN_DISTANCE','签到距离限制(单位：米)','0','500',1,1,'签到距离限制',NOW());

-- 提现金额限制 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MIN_WITHDRAW','最小提现金额(单位：元)','0','1',1,1,'最小提现金额',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MAX_WITHDRAW_M','每月最大提现金额(单位：元)','0','799',1,1,'每月最大提现金额',NOW());

-- 提现次数限制 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('WITHDRAW_FREQUENCY','提现次数限制','0','1',1,1,'提现次数限制(D:日,W:周:M月),只能设定一种限制',NOW());


-- 任务指派状态 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('ASSIGN_STATUS','任务指派状态','1','待处理',1,1,'任务指派状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('ASSIGN_STATUS','任务指派状态','2','预处理',1,2,'任务指派状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('ASSIGN_STATUS','任务指派状态','3','指派成功',1,3,'任务指派状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('ASSIGN_STATUS','任务指派状态','4','无秘客信息',1,4,'任务指派状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('ASSIGN_STATUS','任务指派状态','5','手机号重复',1,5,'任务指派状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('ASSIGN_STATUS','任务指派状态','6','已参加过活动',1,6,'任务指派状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('ASSIGN_STATUS','任务指派状态','7','未找到门店',1,7,'任务指派状态',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('ASSIGN_STATUS','任务指派状态','8','分派失败',1,7,'任务指派状态',NOW());

-- 商户类型 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MER_TYPE','商户类型','1','餐饮商户',1,1,'商户类型-餐饮商户',NOW());

-- 商户等级 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MER_LEVEL','商户等级','1','1',1,1,'商户等级',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MER_LEVEL','商户等级','2','2',1,2,'商户等级',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MER_LEVEL','商户等级','3','3',1,3,'商户等级',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MER_LEVEL','商户等级','4','4',1,4,'商户等级',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('MER_LEVEL','商户等级','5','5',1,5,'商户等级',NOW());

-- 推送类型 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('ASSIGN_TYPE','推送类型','1','批量推送',1,1,'推送类型-批量',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('ASSIGN_TYPE','推送类型','2','单独推送',1,2,'推送类型-单独',NOW());


-- 检查重复任务天数 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('REPEAT_TASK_DAY','检查重复任务天数','0','60',1,1,'检查任务重复天数范围（单位：日）',NOW());


-- 报表状态 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('REPORT_STATUS','报表状态','1','已领取',1,1,'报表状态-已领取',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('REPORT_STATUS','报表状态','2','已审核',1,2,'报表状态-已审核',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('REPORT_STATUS','报表状态','3','待审核',1,3,'报表状态-待审核',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('REPORT_STATUS','报表状态','4','退回修改',1,4,'报表状态-退回修改',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('REPORT_STATUS','报表状态','5','取消',1,5,'报表状态-取消',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('REPORT_STATUS','报表状态','6','失败',1,6,'报表状态-失败',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('REPORT_STATUS','报表状态','7','超时',1,7,'报表状态-超时',NOW());


-- 报表排序 --
INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('REPORT_SORT','报表排序','1','升序',1,1,'报表排序-升序',NOW());

INSERT INTO SYSBOOK(TYPE_CODE,TYPE_NAME,LIST_CODE,LIST_NAME,STATUS,PRI,REMARK,CREATE_TIME)
VALUES('REPORT_SORT','报表排序','2','降序',1,2,'报表排序-降序',NOW());

/*==============================================================*/
/* Index: I_SYSBOOK_TYPECODE                                    */
/*==============================================================*/
create index I_SYSBOOK_TYPECODE on SYSBOOK
(
   TYPE_CODE
);

/*==============================================================*/
/* Index: U_SYSBOOK_TYPELIST                                    */
/*==============================================================*/
create unique index U_SYSBOOK_TYPELIST on SYSBOOK
(
   TYPE_CODE,
   LIST_CODE
);

/*==============================================================*/
/* Table: SYS_FUNCTION                                          */
/*==============================================================*/
create table SYS_FUNCTION
(
   ID                   bigint not null auto_increment,
   NAME                 varchar(50) comment '菜单名称',
   CODE                 varchar(40),
   ACTION               longtext comment '相应的操作，如地址',
   ICON_CLASS           varchar(50) comment '图标CSS类',
   LINK_TARGET          varchar(1) comment 'html连接的target属性
            0:框架打开
            1:新窗口打开',
   SORT                 int comment '显示顺序',
   TYPE                 int comment '类型
            1:菜单
            2:操作功能',
   PARENT_ID            bigint comment '上级菜单ID，如果无父节点，则为空',
   STATUS               tinyint not null comment '状态
            1：有效
            0：无效',
   REMARK               varchar(200) comment '备注',
   CREATE_TIME          datetime comment '创建时间',
   CREATE_USER          varchar(50) comment '创建用户',
   UPDATE_TIME          datetime comment '修改时间',
   UPDATE_USER          varchar(50) comment '修改用户',
   primary key (ID)
);

alter table SYS_FUNCTION comment '系统菜单表';

/*==============================================================*/
/* Index: U_FUNC_CODE                                           */
/*==============================================================*/
create unique index U_FUNC_CODE on SYS_FUNCTION
(
   CODE
);

/*==============================================================*/
/* Table: SYS_ROLE                                              */
/*==============================================================*/
create table SYS_ROLE
(
   ID                   bigint not null auto_increment,
   CODE                 varchar(20) comment '角色编码',
   NAME                 varchar(50) not null comment '角色名称',
   REMARK               varchar(200) comment '备注',
   STATUS               tinyint not null comment '状态
            1：有效
            0：无效',
   CREATE_TIME          datetime comment '创建时间',
   CREATE_USER          varchar(50) comment '创建用户',
   UPDATE_TIME          datetime comment '修改时间',
   UPDATE_USER          varchar(50) comment '修改用户',
   primary key (ID)
);

alter table SYS_ROLE comment '系统角色表';

/*==============================================================*/
/* Index: U_ROLE_NAME                                           */
/*==============================================================*/
create unique index U_ROLE_NAME on SYS_ROLE
(
   NAME
);

/*==============================================================*/
/* Table: SYS_ROLE_FUNC                                         */
/*==============================================================*/
create table SYS_ROLE_FUNC
(
   ROLE_ID              bigint not null,
   FUNC_ID              bigint not null,
   primary key (ROLE_ID, FUNC_ID)
);

alter table SYS_ROLE_FUNC comment '角色菜单关联表';

/*==============================================================*/
/* Table: SYS_USER                                              */
/*==============================================================*/
create table SYS_USER
(
   ID                   bigint not null auto_increment,
   USER_NAME            varchar(50) not null comment '用户名',
   PASSWORD             varchar(100) not null comment '密码',
   AVATAR               varchar(200) comment '头像',
   NAME                 varchar(20) comment '姓名',
   EMAIL                varchar(200) comment 'EMAIL',
   PHONE                varchar(20) comment '联系电话',
   LAST_LOGIN_TIME      datetime comment '最后登录时间',
   LAST_LOGIN_IP        varchar(20) comment '最后登录IP',
   STATUS               tinyint not null comment '状态
            1：有效
            0：无效',
   REMARK               varchar(200) comment '备注',
   CREATE_TIME          datetime comment '创建时间',
   CREATE_USER          varchar(50) comment '创建用户',
   UPDATE_TIME          datetime comment '修改时间',
   UPDATE_USER          varchar(50) comment '修改用户',
   VERSION              bigint,
   primary key (ID)
);

alter table SYS_USER comment '系统用户表';

/*==============================================================*/
/* Index: U_USER_NAME                                           */
/*==============================================================*/
create unique index U_USER_NAME on SYS_USER
(
   USER_NAME
);

/*==============================================================*/
/* Table: SYS_USER_ROLE                                         */
/*==============================================================*/
create table SYS_USER_ROLE
(
   USER_ID              bigint not null comment '用户ID',
   ROLE_ID              bigint not null comment '角色ID',
   primary key (USER_ID, ROLE_ID)
);

alter table SYS_USER_ROLE comment '用户角色关系表';

