-- 初始用户 admin 密码 abcd@1234 --
DELETE FROM SYS_USER;
INSERT INTO SYS_USER(ID,USER_NAME,PASSWORD,NAME,STATUS,CREATE_TIME,CREATE_USER,VERSION)
VALUES(1,'admin','$2a$10$PC5UKBPOnydpSVnm8.EOZe2NgRIf94NVt.y1B9jcyzwvcjm4BM4/e','管理员',1,NOW(),'admin',1);

-- 初始功能菜单 --
DELETE FROM SYS_FUNCTION;

-- 系统管理 一级菜单 --
INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(10,'sys','系统管理','example',1,1,null,1,now(),'admin');

-- 数据字典 二级菜单 --
INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(1001,'sysbook','数据字典','education',1,1,10,1,now(),'admin');

-- 数据字典功能URL --
INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100101,'sysbook:create','新增数据字典','/api/sys/sysbook/create',null,null,2,1001,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100102,'sysbook:list','查询数据字典','/api/sys/sysbook/list',null,null,2,1001,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100103,'sysbook:update','修改数据字典','/api/sys/sysbook/update',null,null,2,1001,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100104,'sysbook:delete','删除数据字典','/api/sys/sysbook/delete/{id}',null,null,2,1001,1,now(),'admin');

-- 角色管理  二级菜单 --
INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(1002,'sysrole','角色管理','peoples',1,1,10,1,now(),'admin');

-- 角色管理功能URL --
INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100201,'sysrole:create','新增角色','/api/sys/role/create',null,null,2,1002,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100202,'sysrole:list','查询角色','/api/sys/role/list',null,null,2,1002,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100203,'sysrole:update','修改角色','/api/sys/role/update',null,null,2,1002,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100204,'sysrole:invalid','作废角色','/api/sys/role/invalid/{id}',null,null,2,1002,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100205,'sysrole:menuTree','获取菜单树','/api/sys/role/menuTree',null,null,2,1002,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100206,'sysrole:roleMnue','获取角色菜单','/api/sys/role/roleMenus/{roleId}',null,null,2,1002,1,now(),'admin');

-- 用户管理 二级菜单 --
INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(1003,'sysuser','用户管理','user',1,1,10,1,now(),'admin');

-- 角色管理功能URL --
INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100301,'sysuser:create','新增用户','/api/sys/user/create',null,null,2,1003,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100302,'sysuser:list','查询用户','/api/sys/user/list',null,null,2,1003,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100303,'sysuser:update','修改用户','/api/sys/user/update',null,null,2,1003,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100304,'sysuser:invalid','作废用户','/api/sys/user/invalid/{id}',null,null,2,1003,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100305,'sysuser:allRole','获取全部角色','/api/sys/role/all',null,null,2,1003,1,now(),'admin');

INSERT INTO SYS_FUNCTION(ID,CODE,TITLE,PATH,ICON,SORT,TYPE,PARENT_ID,STATUS,CREATE_TIME,CREATE_USER)
VALUES(100306,'sysuser:userRoles','获取用户角色','/api/sys/role/userRoles/{userId}',null,null,2,1003,1,now(),'admin');

-- 初始角色 Admin -- 
DELETE FROM SYS_ROLE;
INSERT INTO SYS_ROLE(ID,CODE,NAME,STATUS,CREATE_TIME,CREATE_USER) VALUES(1,'ROLE_ADMIN','管理员',1,now(),'admin');

-- 初始化Admin角色关联 --
DELETE  FROM SYS_USER_ROLE;
INSERT INTO SYS_USER_ROLE(USER_ID,ROLE_ID)VALUES(1,1);

-- 初始化Admin角色功能
DELETE FROM SYS_ROLE_FUNC;
INSERT INTO SYS_ROLE_FUNC SELECT 1,ID FROM SYS_FUNCTION WHERE ID=10 OR PARENT_ID=10;